services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ${OLLAMA_VOLUME_PATH:-ollama}:/root/.ollama

  openui:
    container_name: openui
    image: ghcr.io/wandb/openui:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7878:7878"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OPENAI_API_KEY
      - ANTHROPIC_API_KEY
      - GROQ_API_KEY
    env_file:
      - .env

volumes:
  ollama:
